class LanguageOption {
  final String code;
  final String name;
  final String ttsLocale;
  const LanguageOption(this.code, this.name, this.ttsLocale);
}

class AppLocalization {
  static const List<LanguageOption> supportedLanguages = [
    LanguageOption('ar', 'العربية', 'ar-EG'),
    LanguageOption('en', 'English', 'en-US'),
    LanguageOption('fr', 'Français', 'fr-FR'),
    LanguageOption('de', 'Deutsch', 'de-DE'),
    LanguageOption('es', 'Español', 'es-ES'),
    LanguageOption('it', 'Italiano', 'it-IT'),
    LanguageOption('ru', 'Русский', 'ru-RU'),
    LanguageOption('zh', '中文', 'zh-CN'),
    LanguageOption('ja', '日本語', 'ja-JP'),
    LanguageOption('ko', '한국어', 'ko-KR'),
    LanguageOption('hi', 'हिन्दी', 'hi-IN'),
    LanguageOption('tr', 'Türkçe', 'tr-TR'),
  ];

  static bool isRtl(String code) => code.toLowerCase() == 'ar';

  static String tr(String lang, String key) {
    final l = lang.toLowerCase();
    final map = _translations[l] ?? _translations['en']!;
    return map[key] ?? _translations['en']![key] ?? key;
  }

  static final Map<String, Map<String, String>> _translations = {
    'ar': {
      'appName': 'نوفيرا',
      'tagline': 'ذكاء المعلومات الصحية المبني على الأدلة',
      'nav_home': 'الرئيسية',
      'nav_sources': 'المصادر',
      'nav_safety': 'الأمان',
      'nav_services': 'الخدمات',
      'nav_chat': 'المحادثة',
      'new_chat': 'محادثة طبية جديدة',
      'chat_history': 'سجل المحادثات',
      'pinned': '📌 المثبتة',
      'recent': '🕒 الأخيرة',
      'no_history': 'لا توجد محادثات سابقة بعد',
      'emergency': 'طوارئ',
      'sign_in': 'تسجيل الدخول',
      'sign_up': 'إنشاء حساب',
      'sign_out': 'تسجيل الخروج',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'full_name': 'الاسم الكامل',
      'confirm_pass': 'تأكيد كلمة المرور',
      'auth_subtitle': 'سجل دخولك لحفظ ومزامنة استشاراتك الطبية عبر جميع أجهزتك',
      'auth_err_empty': 'يرجى إدخال بريد إلكتروني صحيح وكلمة مرور (4 أحرف على الأقل)',
      'auth_err_match': 'كلمتا المرور غير متطابقتين',
      'auth_success': 'تم تسجيل الدخول بنجاح! مرحباً بك في نوفيرا',
      'hero_badge': '✨ الأدلة الطبية قبل الإجابات',
      'hero_title': 'مساعدك الصحي الذكي المدعوم بالأدلة العلمية',
      'hero_desc': 'احصل على إجابات طبية دقيقة وموثقة من أكبر الهيئات الصحية العالمية مثل منظمة الصحة العالمية ومايو كلينك، مع التزام كامل بمعايير الأمان السريري.',
      'start_chat_btn': 'ابدأ المحادثة الذكية',
      'explore_services_btn': 'احجز الخدمات الطبية بخصم',
      'care_signal': 'إشارة الرعاية الآمنة',
      'care_title': 'مفيد، شفاف، وحذر سريرياً.',
      'grounded_title': 'إجابات موثقة بالمراجع الرسمية',
      'grounded_desc': 'كل إجابة تستند إلى أدلة طبية معتمدة مع عرض الروابط الرسمية للمصادر.',
      'emerg_aware_title': 'استشعار ذكي لحالات الطوارئ',
      'emerg_aware_desc': 'يرصد النظام الأعراض الحرجة ويوجهك فوراً لأرقام الإسعاف المحلية.',
      'welcome_chat': 'مرحباً بك في نوفيرا 👋 اسأل أي سؤال صحي بأي لغة وسأقدم لك إجابة موثقة بالمصادر الطبية المعتمدة.',
      'input_hint': 'اكتب سؤالك الصحي أو الأعراض هنا...',
      'thinking': 'جاري تحليل السؤال ومراجعة المصادر الطبية الموثقة...',
      'q1': 'ما هي العلامات التحذيرية للسكتة الدماغية؟',
      'q2': 'ما هو النظام الغذائي المناسب لمرضى السكري؟',
      'q3': 'كيف يحافظ النشاط البدني على صحة القلب؟',
      'sources_badge': '🌐 هيئات طبية عالمية معتمدة',
      'sources_title': 'المصادر الطبية الموثوقة',
      'sources_desc': 'أعلى المؤسسات الصحية والبحثية العالمية التي يستند إليها محرك نوفيرا لضمان الدقة السريرية.',
      'visit_site': 'زيارة الموقع الرسمي ↗',
      'safety_badge': '🛡️ الأمان، النطاق، والشفافية',
      'safety_title': 'المعلومات الصحية الموثوقة تحتاج لحدود واضحة.',
      'safety_desc': 'صُمم نوفيرا لمساعدتك على فهم المعلومات الطبية المعتمدة، وليس ليحل محل الطبيب المختص أو خدمات الطوارئ.',
      'safety_emerg_box': 'قد تكون هذه حالة طارئة! اتصل برقم الإسعاف المحلي فوراً إذا كنت تشعر بأعراض حادة أو خطيرة.',
      'call_emerg_now': 'الاتصال بخدمات الطوارئ الآن',
      'not_doc_title': '🛡️ ليس طبيباً مشخصاً',
      'not_doc_desc': 'لا يقوم نوفيرا بتشخيص الأمراض سريرياً أو كتابة وصفات دوائية شخصية.',
      'evidence_title': '📖 أدلة ومراجع معلنة',
      'evidence_desc': 'جميع الإجابات مربوطة بمصادرها الرسمية مع روابط مباشرة للمراجعة.',
      'escalation_title': '⚠️ تصعيد فوري للطوارئ',
      'escalation_desc': 'رصد تلقائي للأعراض الحرجة وتوجيه فوري لطلب الرعاية العاجلة.',
      'services_badge': '⚡ خدمات طبية معتمدة بخصم 50%',
      'services_title': 'احجز المعامل والأشعة والعيادات بأسعار مخفضة',
      'services_desc': 'خصومات حصرية لمستخدمي نوفيرا لدى أكبر المعامل ومراكز الأشعة والمستشفيات المعتمدة في مصر.',
      'tab_labs': '🧪 المعامل',
      'tab_scans': '☢️ مراكز الأشعة',
      'tab_clinics': '🏥 العيادات والمستشفيات',
      'book_whatsapp': 'تأكيد الحجز عبر واتساب',
      'payment_note': 'الدفع عبر فودافون كاش أو إنستاباي',
      'call_now': 'اتصل الآن:',
      'emerg_modal_title': '⚠️ طوارئ / Emergency',
      'location_detected': 'الدولة المكتشفة:',
      'local_ambulance': 'رقم الإسعاف المحلي:',
      'call_ambulance': 'اتصل بالإسعاف الآن',
      'cancel': 'إلغاء',
      'server_settings': 'عنوان خادم الذكاء الاصطناعي (Backend URL)',
      'save': 'حفظ',
      'feedback_thanks': 'شكراً لتقييمك! تم حفظ ملاحظتك.',
      'copied': 'تم نسخ الإجابة إلى الحافظة',
    },
    'en': {
      'appName': 'Nuvira',
      'tagline': 'Evidence-Grounded Health Intelligence',
      'nav_home': 'Home',
      'nav_sources': 'Sources',
      'nav_safety': 'Safety',
      'nav_services': 'Services',
      'nav_chat': 'AI Chat',
      'new_chat': 'New Conversation',
      'chat_history': 'CHAT HISTORY',
      'pinned': '📌 PINNED',
      'recent': '🕒 RECENT',
      'no_history': 'No previous conversations yet',
      'emergency': 'Emergency',
      'sign_in': 'Sign In',
      'sign_up': 'Sign Up',
      'sign_out': 'Sign Out',
      'email': 'Email Address',
      'password': 'Password',
      'full_name': 'Full Name',
      'confirm_pass': 'Confirm Password',
      'auth_subtitle': 'Sign in to sync and save your medical consultations across devices',
      'auth_err_empty': 'Please enter a valid email and password (min 4 chars)',
      'auth_err_match': 'Passwords do not match',
      'auth_success': 'Signed in successfully! Welcome to Nuvira',
      'hero_badge': '✨ EVIDENCE BEFORE ANSWERS',
      'hero_title': 'Your Evidence-Grounded Health Assistant',
      'hero_desc': 'Get clear health information grounded in trusted medical sources like WHO and Mayo Clinic, with strict clinical safety boundaries.',
      'start_chat_btn': 'Start AI Consultation',
      'explore_services_btn': 'Explore Medical Services',
      'care_signal': 'CARE SIGNAL',
      'care_title': 'Helpful, transparent, careful.',
      'grounded_title': 'Grounded answers',
      'grounded_desc': 'Retrieved clinical evidence informs every answer with official source links.',
      'emerg_aware_title': 'Emergency-aware by design',
      'emerg_aware_desc': 'Potential emergency signals trigger an immediate local ambulance alert.',
      'welcome_chat': 'Welcome to Nuvira 👋 Ask any health question and I will provide answers backed by verified clinical sources.',
      'input_hint': 'Ask a health question or describe symptoms...',
      'thinking': 'Analyzing symptoms & reviewing verified medical sources...',
      'q1': 'What are warning signs of a stroke?',
      'q2': 'General diet guidelines for diabetes?',
      'q3': 'How does physical activity support heart health?',
      'sources_badge': '🌐 VERIFIED AUTHORITIES',
      'sources_title': 'Trusted Global Sources',
      'sources_desc': 'The top-tier healthcare authorities and research institutions backing our clinical accuracy.',
      'visit_site': 'VISIT OFFICIAL SITE ↗',
      'safety_badge': '🛡️ SAFETY, SCOPE & TRANSPARENCY',
      'safety_title': 'Useful health information needs clear boundaries.',
      'safety_desc': 'Nuvira is designed to help people understand trusted source material, not to replace a doctor or emergency care.',
      'safety_emerg_box': 'This may be an emergency! Contact your local ambulance immediately if you feel severely unwell.',
      'call_emerg_now': 'Call emergency services',
      'not_doc_title': '🛡️ Not a doctor',
      'not_doc_desc': 'Nuvira cannot diagnose conditions, examine you, or prescribe medication doses.',
      'evidence_title': '📖 Evidence shown',
      'evidence_desc': 'Answers are grounded in retrieved source material with clear official links.',
      'escalation_title': '⚠️ Emergency escalation',
      'escalation_desc': 'Potential emergency patterns trigger a prominent warning before any response.',
      'services_badge': '⚡ Certified Medical Services (50% OFF)',
      'services_title': 'Book Labs, Scans & Clinics at Discounted Prices',
      'services_desc': 'Exclusive discounts for Nuvira users across top certified laboratories, scan centers, and hospitals.',
      'tab_labs': '🧪 Laboratories',
      'tab_scans': '☢️ Scan Centers',
      'tab_clinics': '🏥 Clinics',
      'book_whatsapp': 'Confirm Booking (WhatsApp)',
      'payment_note': 'Payment via Vodafone Cash or InstaPay',
      'call_now': 'Call Now:',
      'emerg_modal_title': '⚠️ Emergency / طوارئ',
      'location_detected': 'Location detected:',
      'local_ambulance': 'Local Ambulance:',
      'call_ambulance': 'Call Ambulance',
      'cancel': 'Cancel',
      'server_settings': 'AI Backend Server URL',
      'save': 'Save',
      'feedback_thanks': 'Thank you for your feedback!',
      'copied': 'Copied to clipboard',
    },
    'fr': {
      'appName': 'Nuvira',
      'tagline': 'Intelligence de santé fondée sur des preuves',
      'nav_home': 'Accueil',
      'nav_sources': 'Sources',
      'nav_safety': 'Sécurité',
      'nav_services': 'Services',
      'nav_chat': 'Chat IA',
      'new_chat': 'Nouvelle discussion',
      'chat_history': 'HISTORIQUE',
      'pinned': '📌 ÉPINGLÉS',
      'recent': '🕒 RÉCENTS',
      'no_history': 'Aucune discussion précédente',
      'emergency': 'Urgence',
      'sign_in': 'Connexion',
      'sign_up': 'Inscription',
      'sign_out': 'Déconnexion',
      'email': 'Adresse e-mail',
      'password': 'Mot de passe',
      'full_name': 'Nom complet',
      'confirm_pass': 'Confirmer le mot de passe',
      'auth_subtitle': 'Connectez-vous pour synchroniser vos consultations médicales',
      'hero_badge': '✨ LES PREUVES AVANT LES RÉPONSES',
      'hero_title': 'Votre Assistant Santé Fondé sur des Preuves',
      'hero_desc': 'Obtenez des informations médicales fiables issues de l’OMS et de la Mayo Clinic en toute sécurité.',
      'start_chat_btn': 'Démarrer la consultation IA',
      'explore_services_btn': 'Services Médicaux',
      'care_signal': 'SIGNAL DE SOIN',
      'care_title': 'Utile, transparent, prudent.',
      'grounded_title': 'Réponses référencées',
      'grounded_desc': 'Chaque réponse est appuyée par des sources médicales officielles.',
      'emerg_aware_title': 'Détection des urgences',
      'emerg_aware_desc': 'Alerte immédiate avec numéro d’ambulance local en cas de symptômes critiques.',
      'welcome_chat': 'Bienvenue sur Nuvira 👋 Posez votre question médicale.',
      'input_hint': 'Posez une question de santé...',
      'thinking': 'Analyse des sources médicales vérifiées...',
      'q1': 'Quels sont les signes d’un AVC ?',
      'q2': 'Quel régime alimentaire pour le diabète ?',
      'q3': 'Comment protéger la santé cardiaque ?',
      'sources_badge': '🌐 AUTORITÉS VÉRIFIÉES',
      'sources_title': 'Sources Médicales Mondiales',
      'sources_desc': 'Les institutions médicales de référence mondiale garantissant notre précision.',
      'visit_site': 'VISITER LE SITE OFFICIEL ↗',
      'safety_badge': '🛡️ SÉCURITÉ ET TRANSPARENCE',
      'safety_title': 'Une information médicale fiable nécessite des limites claires.',
      'safety_desc': 'Nuvira vous aide à comprendre les sources médicales mais ne remplace pas un médecin.',
      'safety_emerg_box': 'Ceci peut être une urgence ! Appelez les secours locaux immédiatement.',
      'call_emerg_now': 'Appeler les urgences',
      'not_doc_title': '🛡️ Pas un médecin',
      'not_doc_desc': 'Nuvira ne pose pas de diagnostic médical et ne prescrit pas de médicaments.',
      'evidence_title': '📖 Preuves affichées',
      'evidence_desc': 'Toutes les réponses incluent des liens vers les sources officielles.',
      'escalation_title': '⚠️ Alerte d’urgence',
      'escalation_desc': 'Orientation immédiate vers les services d’urgence en cas de danger.',
      'services_badge': '⚡ Services Médicaux Certifiés (-50%)',
      'services_title': 'Réservez Laboratoires, Radios et Cliniques à prix réduit',
      'services_desc': 'Réductions exclusives dans les meilleurs laboratoires et hôpitaux certifiés.',
      'tab_labs': '🧪 Laboratoires',
      'tab_scans': '☢️ Radiologie',
      'tab_clinics': '🏥 Cliniques',
      'book_whatsapp': 'Réserver via WhatsApp',
      'payment_note': 'Paiement via Vodafone Cash ou InstaPay',
      'call_now': 'Appeler :',
      'emerg_modal_title': '⚠️ Urgence / Emergency',
      'location_detected': 'Pays détecté :',
      'local_ambulance': 'Ambulance locale :',
      'call_ambulance': 'Appeler l’ambulance',
      'cancel': 'Annuler',
    },
    'de': {
      'appName': 'Nuvira',
      'tagline': 'Evidenzbasierte Gesundheitsintelligenz',
      'nav_home': 'Start',
      'nav_sources': 'Quellen',
      'nav_safety': 'Sicherheit',
      'nav_services': 'Dienste',
      'nav_chat': 'KI-Chat',
      'new_chat': 'Neues Gespräch',
      'chat_history': 'VERLAUF',
      'pinned': '📌 ANGEHEFTET',
      'recent': '🕒 ZULETZT',
      'emergency': 'Notfall',
      'sign_in': 'Anmelden',
      'sign_up': 'Registrieren',
      'sign_out': 'Abmelden',
      'email': 'E-Mail-Adresse',
      'password': 'Passwort',
      'full_name': 'Vollständiger Name',
      'confirm_pass': 'Passwort bestätigen',
      'auth_subtitle': 'Melden Sie sich an, um Ihre medizinischen Sitzungen zu speichern',
      'hero_badge': '✨ EVIDENZ VOR ANTWORTEN',
      'hero_title': 'Ihr evidenzbasierter Gesundheitsassistent',
      'hero_desc': 'Verlässliche Gesundheitsinformationen basierend auf WHO, Mayo Clinic und NIH.',
      'start_chat_btn': 'KI-Beratung starten',
      'explore_services_btn': 'Medizinische Dienste',
      'care_signal': 'SICHERHEITSSIGNAL',
      'care_title': 'Hilfreich, transparent, sorgfältig.',
      'grounded_title': 'Belegte Antworten',
      'grounded_desc': 'Jede Antwort enthält überprüfbare medizinische Originalquellen.',
      'emerg_aware_title': 'Notfall-Erkennung',
      'emerg_aware_desc': 'Sofortige Anzeige der örtlichen Notrufnummer bei kritischen Symptomen.',
      'welcome_chat': 'Willkommen bei Nuvira 👋 Stellen Sie Ihre Gesundheitsfrage.',
      'input_hint': 'Gesundheitsfrage eingeben...',
      'thinking': 'Medizinische Quellen werden analysiert...',
      'q1': 'Was sind Warnzeichen eines Schlaganfalls?',
      'q2': 'Ernährungstipps bei Diabetes?',
      'q3': 'Wie schützt Bewegung das Herz?',
      'sources_badge': '🌐 ZERTIFIZIERTE QUELLEN',
      'sources_title': 'Vertrauenswürdige Weltquellen',
      'sources_desc': 'Die führenden Gesundheitsorganisationen hinter unserer klinischen Genauigkeit.',
      'visit_site': 'OFFIZIELLE WEBSITE ↗',
      'safety_badge': '🛡️ SICHERHEIT & TRANSPARENZ',
      'safety_title': 'Gesundheitsinformationen brauchen klare Grenzen.',
      'safety_desc': 'Nuvira ersetzt keinen Arzt und keine Notaufnahme.',
      'safety_emerg_box': 'Dies könnte ein Notfall sein! Rufen Sie sofort den Rettungsdienst.',
      'call_emerg_now': 'Notruf wählen',
      'not_doc_title': '🛡️ Kein Arzt',
      'not_doc_desc': 'Keine klinische Diagnose oder Medikamentenverschreibung.',
      'evidence_title': '📖 Sichtbare Quellen',
      'evidence_desc': 'Direkte Links zu offiziellen medizinischen Leitlinien.',
      'escalation_title': '⚠️ Notfall-Warnung',
      'escalation_desc': 'Automatische Weiterleitung an lokale Notrufnummern.',
      'services_badge': '⚡ Zertifizierte Medizinische Dienste',
      'services_title': 'Labore, Radiologie & Kliniken mit Rabatt buchen',
      'services_desc': 'Exklusive Rabatte bei führenden zertifizierten Laboren und Kliniken.',
      'tab_labs': '🧪 Labore',
      'tab_scans': '☢️ Radiologie',
      'tab_clinics': '🏥 Kliniken',
      'book_whatsapp': 'Über WhatsApp buchen',
      'call_now': 'Anrufen:',
      'call_ambulance': 'Krankenwagen rufen',
      'cancel': 'Abbrechen',
    },
    'es': {
      'appName': 'Nuvira',
      'tagline': 'Inteligencia de salud basada en evidencia',
      'nav_home': 'Inicio',
      'nav_sources': 'Fuentes',
      'nav_safety': 'Seguridad',
      'nav_services': 'Servicios',
      'nav_chat': 'Chat IA',
      'new_chat': 'Nueva consulta',
      'chat_history': 'HISTORIAL',
      'pinned': '📌 FIJADOS',
      'recent': '🕒 RECIENTES',
      'emergency': 'Emergencia',
      'sign_in': 'Iniciar Sesión',
      'sign_up': 'Registrarse',
      'sign_out': 'Cerrar Sesión',
      'email': 'Correo electrónico',
      'password': 'Contraseña',
      'full_name': 'Nombre completo',
      'confirm_pass': 'Confirmar contraseña',
      'hero_badge': '✨ EVIDENCIA ANTES DE RESPUESTAS',
      'hero_title': 'Tu Asistente de Salud Basado en Evidencia',
      'hero_desc': 'Información médica clara respaldada por la OMS, Mayo Clinic y NIH.',
      'start_chat_btn': 'Iniciar consulta IA',
      'explore_services_btn': 'Servicios Médicos',
      'care_signal': 'SEÑAL DE CUIDADO',
      'care_title': 'Útil, transparente y seguro.',
      'grounded_title': 'Respuestas fundamentadas',
      'grounded_desc': 'Cada respuesta muestra enlaces directos a fuentes médicas oficiales.',
      'emerg_aware_title': 'Alerta inteligente de emergencias',
      'emerg_aware_desc': 'Detección inmediata de síntomas críticos y número de ambulancia local.',
      'welcome_chat': 'Bienvenido a Nuvira 👋 Haz tu pregunta de salud.',
      'input_hint': 'Escribe tu consulta médica...',
      'thinking': 'Analizando fuentes médicas verificadas...',
      'q1': '¿Cuáles son los signos de un derrame cerebral?',
      'q2': '¿Dieta recomendada para la diabetes?',
      'q3': '¿Cómo mejora el ejercicio la salud cardíaca?',
      'sources_badge': '🌐 AUTORIDADES MÉDICAS',
      'sources_title': 'Fuentes Globales Confiables',
      'sources_desc': 'Las instituciones científicas que respaldan nuestra precisión clínica.',
      'safety_badge': '🛡️ SEGURIDAD Y TRANSPARENCIA',
      'safety_title': 'La información médica necesita límites claros.',
      'safety_desc': 'Nuvira no reemplaza a un médico ni a los servicios de urgencias.',
      'safety_emerg_box': '¡Esto puede ser una emergencia! Llama a una ambulancia de inmediato.',
      'call_emerg_now': 'Llamar a emergencias',
      'not_doc_title': '🛡️ No es un médico',
      'not_doc_desc': 'No realiza diagnósticos clínicos ni receta medicamentos.',
      'evidence_title': '📖 Evidencia visible',
      'evidence_desc': 'Respuestas vinculadas a guías médicas oficiales.',
      'escalation_title': '⚠️ Escalada de emergencia',
      'escalation_desc': 'Aviso inmediato ante síntomas de alto riesgo.',
      'services_badge': '⚡ Servicios Médicos Certificados',
      'services_title': 'Reserva Laboratorios, Escáneres y Clínicas con descuento',
      'services_desc': 'Descuentos exclusivos en los mejores laboratorios y hospitales.',
      'tab_labs': '🧪 Laboratorios',
      'tab_scans': '☢️ Radiología',
      'tab_clinics': '🏥 Clínicas',
      'book_whatsapp': 'Confirmar por WhatsApp',
      'call_ambulance': 'Llamar ambulancia',
      'cancel': 'Cancelar',
    },
    'it': {
      'nav_home': 'Home',
      'nav_sources': 'Fonti',
      'nav_safety': 'Sicurezza',
      'nav_services': 'Servizi',
      'nav_chat': 'Chat IA',
      'new_chat': 'Nuova chat',
      'chat_history': 'CRONOLOGIA',
      'pinned': '📌 FISSATI',
      'recent': '🕒 RECENTI',
      'emergency': 'Emergenza',
      'sign_in': 'Accedi',
      'sign_up': 'Registrati',
      'hero_badge': '✨ PROVE PRIMA DELLE RISPOSTE',
      'hero_title': 'Il tuo Assistente Sanitario Basato sulle Prove',
      'hero_desc': 'Informazioni mediche affidabili basate su OMS, Mayo Clinic e NIH.',
      'start_chat_btn': 'Inizia consulto IA',
      'explore_services_btn': 'Servizi Medici',
      'welcome_chat': 'Benvenuto su Nuvira 👋 Fai una domanda sulla salute.',
      'input_hint': 'Scrivi la tua domanda medica...',
      'thinking': 'Analisi delle fonti mediche in corso...',
      'sources_title': 'Fonti Mediche Ufficiali',
      'safety_title': 'La sicurezza clinica prima di tutto.',
      'services_title': 'Prenota Laboratori, Analisi e Cliniche con sconto',
      'tab_labs': '🧪 Laboratori',
      'tab_scans': '☢️ Radiologia',
      'tab_clinics': '🏥 Cliniche',
      'book_whatsapp': 'Prenota su WhatsApp',
      'call_ambulance': 'Chiama Ambulanza',
    },
    'ru': {
      'nav_home': 'Главная',
      'nav_sources': 'Источники',
      'nav_safety': 'Безопасность',
      'nav_services': 'Услуги',
      'nav_chat': 'ИИ-Чат',
      'new_chat': 'Новый диалог',
      'chat_history': 'ИСТОРИЯ ЧАТОВ',
      'pinned': '📌 ЗАКРЕПЛЕННЫЕ',
      'recent': '🕒 НЕДАВНИЕ',
      'emergency': 'Скорая',
      'sign_in': 'Войти',
      'sign_up': 'Регистрация',
      'hero_badge': '✨ ДОКАЗАТЕЛЬНАЯ МЕДИЦИНА',
      'hero_title': 'Ваш медицинский ИИ-помощник на основе фактов',
      'hero_desc': 'Точная медицинская информация на основе данных ВОЗ, Mayo Clinic и NIH.',
      'start_chat_btn': 'Начать консультацию',
      'explore_services_btn': 'Медицинские услуги',
      'welcome_chat': 'Добро пожаловать в Nuvira 👋 Задайте ваш вопрос о здоровье.',
      'input_hint': 'Опишите симптомы или задайте вопрос...',
      'thinking': 'Проверка проверенных медицинских источников...',
      'sources_title': 'Надежные мировые источники',
      'safety_title': 'Клиническая безопасность и прозрачность.',
      'services_title': 'Запись в лаборатории, МРТ и клиники со скидкой',
      'tab_labs': '🧪 Лаборатории',
      'tab_scans': '☢️ Диагностика',
      'tab_clinics': '🏥 Клиники',
      'book_whatsapp': 'Записаться через WhatsApp',
      'call_ambulance': 'Вызвать скорую',
    },
    'zh': {
      'nav_home': '首页',
      'nav_sources': '权威来源',
      'nav_safety': '安全准则',
      'nav_services': '医疗服务',
      'nav_chat': 'AI 问诊',
      'new_chat': '新建对话',
      'chat_history': '历史记录',
      'pinned': '📌 已置顶',
      'recent': '🕒 最近对话',
      'emergency': '紧急呼救',
      'sign_in': '登录',
      'sign_up': '注册账户',
      'hero_badge': '✨ 循证医学优先',
      'hero_title': '基于权威医学证据的 AI 健康助手',
      'hero_desc': '获取来自世界卫生组织 (WHO)、梅奥诊所和 NIH 的可靠医疗健康信息。',
      'start_chat_btn': '开始 AI 健康咨询',
      'explore_services_btn': '浏览折扣医疗服务',
      'welcome_chat': '欢迎使用 Nuvira 👋 请输入您的健康问题，我将为您提供权威医学解答。',
      'input_hint': '输入您的健康问题或症状...',
      'thinking': '正在检索权威医学文献与指南...',
      'sources_title': '全球权威医疗机构来源',
      'safety_title': '明确的临床安全边界与透明度',
      'services_title': '预约认证实验室、影像中心与诊所（享专属折扣）',
      'tab_labs': '🧪 医学检验',
      'tab_scans': '☢️ 影像扫描',
      'tab_clinics': '🏥 专科诊所',
      'book_whatsapp': '通过 WhatsApp 确认预约',
      'call_ambulance': '呼叫救护车',
    },
    'ja': {
      'nav_home': 'ホーム',
      'nav_sources': '情報源',
      'nav_safety': '安全性',
      'nav_services': '医療予約',
      'nav_chat': 'AI相談',
      'new_chat': '新しい相談',
      'chat_history': '相談履歴',
      'pinned': '📌 ピン留め',
      'recent': '🕒 最近の履歴',
      'emergency': '緊急通報',
      'sign_in': 'ログイン',
      'sign_up': '新規登録',
      'hero_badge': '✨ エビデンス重視の医療AI',
      'hero_title': '科学的根拠に基づくAIヘルスケアアシスタント',
      'hero_desc': 'WHOやメイヨークリニックなどの信頼できる医学情報に基づいた回答を提供します。',
      'start_chat_btn': 'AI相談を始める',
      'explore_services_btn': '医療サービスを見る',
      'welcome_chat': 'Nuviraへようこそ 👋 健康に関する質問を入力してください。',
      'input_hint': '症状や健康の質問を入力...',
      'thinking': '信頼できる医学文献を確認中...',
      'sources_title': '信頼できる国際医療情報源',
      'safety_title': '医療安全と透明性のガイドライン',
      'services_title': '提携検査機関・画像診断・クリニックを割引予約',
      'tab_labs': '🧪 検査機関',
      'tab_scans': '☢️️ 画像診断',
      'tab_clinics': '🏥 クリニック',
      'book_whatsapp': 'WhatsAppで予約確定',
      'call_ambulance': '救急車を呼ぶ',
    },
    'ko': {
      'nav_home': '홈',
      'nav_sources': '의학 출처',
      'nav_safety': '안전 수칙',
      'nav_services': '의료 서비스',
      'nav_chat': 'AI 상담',
      'new_chat': '새 상담 시작',
      'chat_history': '상담 기록',
      'pinned': '📌 고정됨',
      'recent': '🕒 최근 기록',
      'emergency': '응급 전화',
      'sign_in': '로그인',
      'sign_up': '회원가입',
      'hero_badge': '✨ 근거 중심 의학 AI',
      'hero_title': '신뢰할 수 있는 의학 근거 기반 AI 건강 비서',
      'hero_desc': 'WHO, 메이요 클리닉 등 검증된 글로벌 의료 기관의 자료를 바탕으로 답변합니다.',
      'start_chat_btn': 'AI 건강 상담 시작',
      'explore_services_btn': '할인 의료 서비스 보기',
      'welcome_chat': 'Nuvira에 오신 것을 환영합니다 👋 건강 질문을 입력해주세요.',
      'input_hint': '증상이나 건강 질문을 입력하세요...',
      'thinking': '검증된 의학 자료를 분석 중입니다...',
      'sources_title': '신뢰할 수 있는 글로벌 의료 출처',
      'safety_title': '명확한 임상 안전 기준과 투명성',
      'services_title': '검사실, 영상의학 및 병원 할인 예약',
      'tab_labs': '🧪 검사실',
      'tab_scans': '☢️ 영상 스캔',
      'tab_clinics': '🏥 클리닉',
      'book_whatsapp': 'WhatsApp으로 예약하기',
      'call_ambulance': '구급차 호출',
    },
    'hi': {
      'nav_home': 'होम',
      'nav_sources': 'स्रोत',
      'nav_safety': 'सुरक्षा',
      'nav_services': 'सेवाएं',
      'nav_chat': 'AI चैट',
      'new_chat': 'नई बातचीत',
      'chat_history': 'चैट इतिहास',
      'pinned': '📌 पिन किए गए',
      'recent': '🕒 हाल ही के',
      'emergency': 'आपातकाल',
      'sign_in': 'लॉग इन करें',
      'sign_up': 'खाता बनाएं',
      'hero_badge': '✨ प्रमाण-आधारित स्वास्थ्य AI',
      'hero_title': 'आपका प्रमाण-आधारित स्वास्थ्य सहायक',
      'hero_desc': 'WHO और मेयो क्लिनिक जैसे विश्वसनीय चिकित्सा स्रोतों से सटीक स्वास्थ्य जानकारी प्राप्त करें।',
      'start_chat_btn': 'AI परामर्श शुरू करें',
      'explore_services_btn': 'चिकित्सा सेवाएं देखें',
      'welcome_chat': 'Nuvira में आपका स्वागत है 👋 अपना स्वास्थ्य प्रश्न पूछें।',
      'input_hint': 'अपना स्वास्थ्य प्रश्न या लक्षण लिखें...',
      'thinking': 'चिकित्सा स्रोतों की जांच की जा रही है...',
      'sources_title': 'विश्वसनीय वैश्विक चिकित्सा स्रोत',
      'safety_title': 'चिकित्सा सुरक्षा और पारदर्शिता',
      'services_title': 'लैब, स्कैन और क्लिनिक छूट पर बुक करें',
      'tab_labs': '🧪 पैथोलॉजी लैब',
      'tab_scans': '☢️ स्कैन सेंटर',
      'tab_clinics': '🏥 क्लिनिक',
      'book_whatsapp': 'WhatsApp द्वारा बुकिंग करें',
      'call_ambulance': 'एम्बुलेंस बुलाएं',
    },
    'tr': {
      'nav_home': 'Ana Sayfa',
      'nav_sources': 'Kaynaklar',
      'nav_safety': 'Güvenlik',
      'nav_services': 'Hizmetler',
      'nav_chat': 'YZ Sohbet',
      'new_chat': 'Yeni Sohbet',
      'chat_history': 'SOHBET GEÇMİŞİ',
      'pinned': '📌 SABİTLENENLER',
      'recent': '🕒 SON SOHBETLER',
      'emergency': 'Acil',
      'sign_in': 'Giriş Yap',
      'sign_up': 'Kayıt Ol',
      'hero_badge': '✨ YANITLARDAN ÖNCE KANIT',
      'hero_title': 'Kanıta Dayalı Yapay Zeka Sağlık Asistanınız',
      'hero_desc': 'DSÖ (WHO) ve Mayo Clinic gibi güvenilir tıbbi kaynaklara dayalı net sağlık bilgileri alın.',
      'start_chat_btn': 'YZ Danışmanlığı Başlat',
      'explore_services_btn': 'Tıbbi Hizmetleri Keşfet',
      'welcome_chat': 'Nuvira’ya Hoş Geldiniz 👋 Sağlık sorunuzu yazın.',
      'input_hint': 'Sağlık sorunuzu veya belirtileri yazın...',
      'thinking': 'Güvenilir tıbbi kaynaklar inceleniyor...',
      'sources_title': 'Güvenilir Küresel Tıbbi Kaynaklar',
      'safety_title': 'Klinik Güvenlik ve Şeffaflık İlkeleri',
      'services_title': 'Laboratuvar, Görüntüleme ve Klinikleri İndirimli Ayırtın',
      'tab_labs': '🧪 Laboratuvarlar',
      'tab_scans': '☢️ Görüntüleme',
      'tab_clinics': '🏥 Klinikler',
      'book_whatsapp': 'WhatsApp ile Randevu Al',
      'call_ambulance': 'Ambulansı Ara',
    },
  };
}
